<?php

session_start();
$movies = require __DIR__ . '/../data/movies.php';
$booking = $_SESSION['booking'] ?? null;
$movie = $booking ? ($movies[$booking['movie_id']] ?? null) : null;
?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Confirmation — KinoMonster</title><link rel="stylesheet" href="../css/main.css"><link rel="stylesheet" href="../css/header.css"><link rel="stylesheet" href="../css/footer.css"><script src="../js/main.js" defer></script></head>
<body><header><nav class="header-nav nav-desktop"><div class="header-nav-elems default-container"><ul><li><a href="../project.html" class="logo"><img src="../photos/logo_kinomonster.svg" alt="KinoMonster"></a></li></ul><ul class="second-menu"><li><a href="search.php">MOVIES</a></li><li><a href="search.php">SEARCH</a></li><li><a href="../login.html">LOG IN</a></li><li><a href="../register.html">REGISTER</a></li></ul></div></nav><nav class="nav-mobile"><div class="header-nav-elems-mobile"><ul><li class="mobile-btn"><img src="../photos/menuicon.svg" alt="Menu"></li><li><a href="../project.html" class="logo"><img src="../photos/logo_kinomonster.svg" alt="KinoMonster"></a></li></ul><ul class="second-menu-mobile"><li><a href="search.php">MOVIES</a></li><li><a href="search.php">SEARCH</a></li><li><a href="../login.html">LOG IN</a></li><li><a href="../register.html">REGISTER</a></li></ul></div></nav></header><main class="flow-page default-container"><section class="confirmation"><?php if ($booking && $movie): ?><div class="success-icon">✓</div><p class="success-label">SUCCESS</p><h1>Your booking is confirmed!</h1><div class="booking-summary"><p><span>Booking ID</span>#<?= htmlspecialchars($booking['id'], ENT_QUOTES, 'UTF-8') ?></p><p><span>Movie</span><?= htmlspecialchars($movie['title'], ENT_QUOTES, 'UTF-8') ?></p><p><span>Date</span><?= htmlspecialchars(date('d.m.Y', strtotime($booking['date'])), ENT_QUOTES, 'UTF-8') ?></p><p><span>Time</span><?= htmlspecialchars($booking['session'], ENT_QUOTES, 'UTF-8') ?></p><p><span>Seats</span><?= htmlspecialchars(implode(', ', $booking['seats']), ENT_QUOTES, 'UTF-8') ?></p></div><a class="text-button" href="search.php">FIND ANOTHER MOVIE</a><?php else: ?><h1>No active booking</h1><a class="text-button" href="search.php">BACK TO SEARCH</a><?php endif; ?></section></main></body></html>